services:
  app:
    build:
      context: .
      dockerfile: build/go/Dockerfile
    volumes:
      - ./go:/go/src/app
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    working_dir: /go/src/app
    command: go run main.go
